config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :comments, :posts do
    resources :votes, except: [:new, :edit, :index, :show]
    resources :comments, except: [:show, :index]
  end

  get 'myposts' => 'posts#index_users_posts'
  get 'mostpopular' => 'posts#popular_posts'

  get 'signup' => 'users#new'
  resources :users
  resources :images

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy
  belongs_to :user

  validates :body, :presence => true

  def post
    commentable.is_a?(Post) ? commentable : commentable.post
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  include ApplicationHelper

  before_action :require_user
  before_action :set_parent, only: [:new, :create, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = @parent.comments.build
  end

  def create
    @comment = @parent.comments.create(comment_params)
    if @comment.save
      redirect_to @comment.post
      flash[:success] = 'Comment was added successfully.'
    else
      redirect_to parent(@parent)
      flash[:error] = 'Comment cannot be empty.'
    end
  end

  def edit
    redirect_non_owner_user @comment
  end

  def update
    if user_owner_of?(@comment)
      if @comment.update_attributes(comment_params)
        redirect_to(@comment.post)
        flash[:success] = 'Comment was updated successfully.'
      else
        redirect_to(@comment.post)
        flash[:error] = 'Comment cannot be empty.'
      end
    end
  end

  def destroy
    if user_owner_of?(@comment)
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @parent }
        format.js { render 'destroy' }
      end
    end
  end

  private

  def redirect_to_post
    redirect_to post_path(Post.find(params[:post_id]))
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def set_parent
    @parent = Post.find_by_id(params[:post_id]) if params[:post_id]
    @parent = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    redirect_to root_path unless defined?(@parent)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def parent(obj)
    obj.is_a?(Post) ? obj : obj.post
  end

end

app/views/comments/_comments.html.erb
<% collection.each do |comment| %>
  <% break if comment.body.nil? && current_user %>
  <div id="comment_<%= comment.id %>" class="well">
    <%= image_tag(comment.user.image.nil? ? no_avatar_image : comment.user.image.picture, class: 'img-thumbnail comment-image') %>
    <span>
      <strong>
        <%= current_user && current_user.id == comment.user.id ? 'Me:' : "#{comment.user.first_name} #{comment.user.last_name}" %>
      </strong>
      <time> <%= comment.created_at.strftime('%m-%d-%Y, at %l:%M%P') %> </time>
    </span>
    <div class="comment-message"><p><%= comment.body %></p></div>
    <div class="comment-panel">
      <%= link_to 'Edit', edit_comment_path(comment) if user_owner_of?(comment) %>
      <%= link_to 'Reply', new_comment_comment_path(comment) if current_user %>
      <%= link_to 'Delete', [comment.post, comment], remote: true, method: :delete if user_owner_of?(comment) %>
      <%= render 'votes/votes', parent: comment, vote_type: 'like' %>
      <%= render 'votes/votes', parent: comment, vote_type: 'dislike' %>
    </div>
    <ul>
      <% unless comment.comments.empty? %>
        <%= render 'comments/comments', :collection => comment.comments %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([parent, parent.comments.build]) do |f| %>
  <% if parent.is_a?(Comment) %> <b> Reply to <%= parent.user.first_name %>: </b> <% end %>
  <%= f.input :body, placeholder: 'Leave a comment...', label: false %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.button :submit, value: 'Send comment' %>
<% end %>

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').fadeOut(700)

app/views/comments/edit.html.erb
<h4>Edit comment</h4>
<%= simple_form_for([@comment]) do |f| %>
  <%= f.input :body, label: false %>
  <%= f.button :submit %>
  <a class="btn btn-default" href="javascript:history.back()">Cancel</a>
<% end %>

app/views/comments/new.html.erb
<%= render 'form', parent: @parent %>