config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :comments, :posts do
    resources :votes, except: [:new, :edit, :index, :show]
    resources :comments, except: [:show, :index]
  end

  get 'myposts' => 'posts#index_users_posts'
  get 'mostpopular' => 'posts#popular_posts'

  get 'signup' => 'users#new'
  resources :users
  resources :images

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlogN" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'BlogN', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Hi, #{current_user.first_name}!", user_path(current_user.id) %></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign up', signup_path %></li>
              <li><%= link_to 'Log in', login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li><%= link_to 'All posts', posts_path %></li>
              <li><%= link_to 'Most popular posts', mostpopular_path %></li>
              <% if current_user %>
                <li><%= link_to 'My posts', myposts_path %></li>
                <li><%= link_to 'My profile', user_path(current_user.id) %></li>
                <li><%= link_to 'Create new post', new_post_path %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Sign up', signup_path %></li>
                <li><%= link_to 'Log in', login_path %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>